// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v3.6.1
// source: v2/applet/chat.proto

package applet

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChatRoomchat = "/applet.v2.ChatRoom/chat"

type ChatRoomHTTPServer interface {
	Chat(context.Context, *ChatWSReq) (*ChatWSResp, error)
}

func RegisterChatRoomHTTPServer(s *http.Server, srv ChatRoomHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v2/ws/chat", _ChatRoom_Chat0_HTTP_Handler(srv))
}

func _ChatRoom_Chat0_HTTP_Handler(srv ChatRoomHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatWSReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatRoomchat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Chat(ctx, req.(*ChatWSReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatWSResp)
		return ctx.Result(200, reply)
	}
}

type ChatRoomHTTPClient interface {
	Chat(ctx context.Context, req *ChatWSReq, opts ...http.CallOption) (rsp *ChatWSResp, err error)
}

type ChatRoomHTTPClientImpl struct {
	cc *http.Client
}

func NewChatRoomHTTPClient(client *http.Client) ChatRoomHTTPClient {
	return &ChatRoomHTTPClientImpl{client}
}

func (c *ChatRoomHTTPClientImpl) Chat(ctx context.Context, in *ChatWSReq, opts ...http.CallOption) (*ChatWSResp, error) {
	var out ChatWSResp
	pattern := "/api/v2/ws/chat"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationChatRoomchat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
