// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v3.6.1
// source: v2/applet/feedback.proto

package applet

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFeedbackCollect = "/applet.v2.Feedback/Collect"

type FeedbackHTTPServer interface {
	Collect(context.Context, *CollectReq) (*emptypb.Empty, error)
}

func RegisterFeedbackHTTPServer(s *http.Server, srv FeedbackHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v2/feedback/collect", _Feedback_Collect0_HTTP_Handler(srv))
}

func _Feedback_Collect0_HTTP_Handler(srv FeedbackHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CollectReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFeedbackCollect)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Collect(ctx, req.(*CollectReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type FeedbackHTTPClient interface {
	Collect(ctx context.Context, req *CollectReq, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type FeedbackHTTPClientImpl struct {
	cc *http.Client
}

func NewFeedbackHTTPClient(client *http.Client) FeedbackHTTPClient {
	return &FeedbackHTTPClientImpl{client}
}

func (c *FeedbackHTTPClientImpl) Collect(ctx context.Context, in *CollectReq, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v2/feedback/collect"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFeedbackCollect))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
