// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v3.6.1
// source: v2/applet/tts.proto

package applet

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTTSServiceGetTTSConfig = "/applet.v2.TTSService/GetTTSConfig"

type TTSServiceHTTPServer interface {
	GetTTSConfig(context.Context, *emptypb.Empty) (*GetTTSConfigResult, error)
}

func RegisterTTSServiceHTTPServer(s *http.Server, srv TTSServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v2/tts/getTTSConfig", _TTSService_GetTTSConfig0_HTTP_Handler(srv))
}

func _TTSService_GetTTSConfig0_HTTP_Handler(srv TTSServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTTSServiceGetTTSConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTTSConfig(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTTSConfigResult)
		return ctx.Result(200, reply)
	}
}

type TTSServiceHTTPClient interface {
	GetTTSConfig(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *GetTTSConfigResult, err error)
}

type TTSServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTTSServiceHTTPClient(client *http.Client) TTSServiceHTTPClient {
	return &TTSServiceHTTPClientImpl{client}
}

func (c *TTSServiceHTTPClientImpl) GetTTSConfig(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*GetTTSConfigResult, error) {
	var out GetTTSConfigResult
	pattern := "/api/v2/tts/getTTSConfig"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTTSServiceGetTTSConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
