// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: v2/applet/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvType int32

const (
	EnvType_prod_m8  EnvType = 0
	EnvType_fit_86   EnvType = 1
	EnvType_prod_251 EnvType = 2
	EnvType_prod_85  EnvType = 3
	EnvType_fit_87   EnvType = 4
	EnvType_sit_134  EnvType = 5
)

// Enum value maps for EnvType.
var (
	EnvType_name = map[int32]string{
		0: "prod_m8",
		1: "fit_86",
		2: "prod_251",
		3: "prod_85",
		4: "fit_87",
		5: "sit_134",
	}
	EnvType_value = map[string]int32{
		"prod_m8":  0,
		"fit_86":   1,
		"prod_251": 2,
		"prod_85":  3,
		"fit_87":   4,
		"sit_134":  5,
	}
)

func (x EnvType) Enum() *EnvType {
	p := new(EnvType)
	*p = x
	return p
}

func (x EnvType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvType) Descriptor() protoreflect.EnumDescriptor {
	return file_v2_applet_common_common_proto_enumTypes[0].Descriptor()
}

func (EnvType) Type() protoreflect.EnumType {
	return &file_v2_applet_common_common_proto_enumTypes[0]
}

func (x EnvType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvType.Descriptor instead.
func (EnvType) EnumDescriptor() ([]byte, []int) {
	return file_v2_applet_common_common_proto_rawDescGZIP(), []int{0}
}

var File_v2_applet_common_common_proto protoreflect.FileDescriptor

var file_v2_applet_common_common_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x76, 0x32, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x74, 0x2e, 0x76, 0x32, 0x2a, 0x56, 0x0a, 0x07, 0x45, 0x6e,
	0x76, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x5f, 0x6d, 0x38,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x69, 0x74, 0x5f, 0x38, 0x36, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x5f, 0x32, 0x35, 0x31, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x64, 0x5f, 0x38, 0x35, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x69, 0x74,
	0x5f, 0x38, 0x37, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x73, 0x69, 0x74, 0x5f, 0x31, 0x33, 0x34,
	0x10, 0x05, 0x42, 0x24, 0x5a, 0x22, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x74, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x65,
	0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v2_applet_common_common_proto_rawDescOnce sync.Once
	file_v2_applet_common_common_proto_rawDescData = file_v2_applet_common_common_proto_rawDesc
)

func file_v2_applet_common_common_proto_rawDescGZIP() []byte {
	file_v2_applet_common_common_proto_rawDescOnce.Do(func() {
		file_v2_applet_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_v2_applet_common_common_proto_rawDescData)
	})
	return file_v2_applet_common_common_proto_rawDescData
}

var file_v2_applet_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v2_applet_common_common_proto_goTypes = []interface{}{
	(EnvType)(0), // 0: applet.v2.EnvType
}
var file_v2_applet_common_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_applet_common_common_proto_init() }
func file_v2_applet_common_common_proto_init() {
	if File_v2_applet_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v2_applet_common_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_applet_common_common_proto_goTypes,
		DependencyIndexes: file_v2_applet_common_common_proto_depIdxs,
		EnumInfos:         file_v2_applet_common_common_proto_enumTypes,
	}.Build()
	File_v2_applet_common_common_proto = out.File
	file_v2_applet_common_common_proto_rawDesc = nil
	file_v2_applet_common_common_proto_goTypes = nil
	file_v2_applet_common_common_proto_depIdxs = nil
}
