server:
  http:
    addr: 0.0.0.0:8300
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9300
    timeout: 10s

app:
  auth:
    key:
    expire: 150000000s
  tts:
    addr: 172.16.23.86:31349
    timeout: 10s
  asr:
    addr: 172.16.23.86:31851
    timeout: 10s
  nlp:
    addr: 172.16.23.86:30811
    timeout: 10s
  feedback:
    addr: 172.16.23.86:31053
    timeout: 10s

data:
  database:
    driver: mysql
    source: root:@tcp(172.16.23.33:3306)/mp
  redis:
    addr: 172.16.23.33:6379
    password:
    read_timeout: 2s
    write_timeout: 2s
    max_retries: 3
  s3:
    endpoint: http://dev-s3.harix.iamidata.com
    access_key: EHNE5AQFQSEXF8TMPJ23
    secret_key: NTxFX1OUACpGKuN9JrMS8N9f39cBcs9bnwX7Ei5K
    bucket: voiceClone
    region: default
    timeout: 30
  train:
    addr: http://172.16.23.85:30221
    notify_addr: http://172.16.23.86:30540

  minio:
    addr: 10.12.32.96:9100
    access_key: Q3AM3UQ867SPQQA43P2F
    secret_key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    region: us-east-1
    bucket: cloudminds

log:
  root_path: runtime/
  save_path: logs/
  save_filename: log
  time_format: 2006-01-02
  max_size: 50
  max_backups: 10
  max_days: 30
  compress: false
  json_format: false
  show_line: true
  log_in_console: true
  level: debug