server:
  http:
    addr: 0.0.0.0:8120
    timeout: 2s
  grpc:
    addr: 0.0.0.0:9120
    timeout: 1s

app:
  auth:
    jwt_key: sQ9QxhasVErjykdG
    jwt_expire: 150000000s
    captcha_redis_expire: 30000000s
    captcha_redis_key:  captcha
    aes_key: NFordaohhdiQMDu5

data:
  database:
    driver: mysql
    source: root:@tcp(172.16.23.33:3306)/test
  redis:
    addr: 172.16.23.33:9527
    password: cloudminds88
    read_timeout: 2s
    write_timeout: 2s
    max_retries: 3
  mongoDB:
    endpoint: http://dev-s3.harix.iamidata.com
    access_key: EHNE5AQFQSEXF8TMPJ23
    secret_key: NTxFX1OUACpGKuN9JrMS8N9f39cBcs9bnwX7Ei5K
    bucket: voiceClone
    region: default
    timeout: 30

log:
  root_path: runtime/
  save_path: logs/
  save_filename: log
  time_format: 2006-01-02
  max_size: 50
  max_backups: 10
  max_days: 30
  compress: false
  json_format: true
  show_line: true
  log_in_console: true
  level: debug